# d2 content/posts/2024/http1.1-from-scratch/reuse.d2 --sketch --theme 201 --pad=20 content/posts/2024/http1.1-from-scratch/reuse.svg

style: {
  fill: transparent
}

shape: sequence_diagram

client
server

connection number 1: {
  client -> server: GET /image1.jpg {
    style.font-color: pink
    style.stroke: red
  }
  server -> client: image1.jpg {
    style.font-color: pink
    style.stroke: red
  }
  client -> server: GET /image2.jpg {
    style.font-color: lightBlue
    style.stroke: blue
  }
  server -> client: image2.jpg {
    style.font-color: lightBlue
    style.stroke: blue
  }
}