baseURL: 'https://sudorandom.dev/'
languageCode: 'en'
theme: "hello-4s3ti"
author: 
  name: "sudorandom"
title: 'sudorandom.dev'
copyright: "All Rights Reserved"
IsMultiLingual: false
defaultContentLanguage: en
enableGitInfo: true

staticDir: 
 - "static"

params:
  Subtitle: "musings of a bored software engineer. Programming, internet, data visualization and more."
  homeSubtitle: "Welcome to my personal notepad that I accidentally published online."
  ReadOtherPosts: "Read some other posts"
  defaultTheme: "dark"
  EnableThemeToggle: false
  gitUrl: "https://github.com/sudorandom/sudorandom.dev/commit/"
  EnableSharingButtons: true
  EnableGlobalLanguageMenu: false
  customCSS: ["/style.css"]
  backgroundImage: "/transparent_geo-mercator-small.webp"
  backgroundEffects: true
  showPosts: true
  tags: false
  contentTypeName: posts
# hideReadMore: true
  ReadMoreText: true
# ReadMore: "foo"
# socialIcons: true
# homeTitle: "Title"
# homeSubtitle: "Subtitle"
  fontAwesome:
    KitURL: "https://kit.fontawesome.com/0ed5cec925.js"
  ShowReadingTime: true
  LastModDisplay: false
  logo:
    logoText: "sudorandom.dev"
    logoCursorColor: "#ffffff"
  social:
    - name: "github"
      url: "https://github.com/sudorandom"
    - name: "mastodon"
      url: "https://infosec.exchange/@sudorandom"
    - name: "twitter"
      url: "https://twitter.com/sudorandom/"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sudorandom/"

  footer:
    showVersion: true
    socialIcons: true
    author: true
    rss: true
    trademark: true
    copyright: true
#   topText:  ["Footer Top text"]
    bottomText: [
      # "Powered by <a href=\"http://gohugo.io\">Hugo</a>", 
      # "with <a href=\"#\">Hello-friend-4s3ti</a>",
    ]

taxonomies:
  category: "categories"

menu:
  main:
    - identifier: "portfolio"
      name: "Portfolio"
      url: "/portfolio/"
      weight: 1
    - identifier: "cv"
      name: "CV"
      url: "https://cv.sudorandom.dev"
      weight: 2
    - identifier: "shop"
      name: "Shop"
      url: "/shop/"
      weight: 3
    - identifier: "posts"
      name: "Archive"
      url: "/posts/"
      weight: 4
