baseURL: 'https://sudorandom.dev/'
languageCode: 'en'
theme: "hello-4s3ti"
title: 'sudorandom.dev'
copyright: "All Rights Reserved"
IsMultiLingual: false
defaultContentLanguage: en
enableGitInfo: true

paginate: 50

staticDir: 
 - "static"
 - "data"

params:
  Subtitle: "Depth-first search into networking, programming, random tech topics."
  Description: "Depth-first search into networking, programming, web development and random tech topics by a bored software engineer."
  homeSubtitle: "Depth-first search into networking, programming, random tech topics."
  ReadOtherPosts: ""
  author:
    name: "sudorandom"
  defaultTheme: "dark"
  EnableThemeToggle: true
  gitUrl: "https://github.com/sudorandom/sudorandom.dev/commit/"
  EnableSharingButtons: false
  EnableGlobalLanguageMenu: false
  customCSS: []
  backgroundImage: "images/transparent_geo-mercator-small.webp"
  backgroundEffects: true
  showPosts: true
  contentTypeName: posts
  hideReadMore: true
  # ReadMoreText: true
# ReadMore: "foo"
# socialIcons: true
# homeTitle: "Title"
# homeSubtitle: "Subtitle"
  fontAwesome:
    KitURL: "https://kit.fontawesome.com/0ed5cec925.js"
  ShowReadingTime: true
  LastModDisplay: false
  logo:
    logoText: "sudorandom.dev"
    logoCursorColor: "#ffffff"
  social:
    - name: "mastodon"
      url: "https://infosec.exchange/@sudorandom"
    - name: "github"
      url: "https://github.com/sudorandom"
    - name: "twitter"
      url: "https://twitter.com/sudorandom/"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sudorandom/"

  footer:
    showVersion: true
    socialIcons: true
    author: true
    rss: true
    trademark: true
    copyright: true
#   topText:  ["Footer Top text"]
    bottomText: [
      # "Powered by <a href=\"http://gohugo.io\">Hugo</a>", 
      # "with <a href=\"#\">Hello-friend-4s3ti</a>",
    ]

taxonomies:
  category: "categories"
  tag: "tags"

permalinks:
  posts: "/posts/:slug/"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 1
    - identifier: "projects"
      name: "Projects"
      url: "/projects/"
      weight: 2
    - identifier: "links"
      name: "Links"
      url: "/links/"
      weight: 3
    - identifier: "updates"
      name: "Updates"
      url: "/updates/"
      weight: 4
    - identifier: "shop"
      name: "Shop"
      url: "/shop/"
      weight: 5

markup:
  tableOfContents:
    endLevel: 4

outputs:
  home: ['html']
  section: ['html']
  taxonomy: ['html']
  term: ['html']

related:
  includeNewer: true
  indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ""
    toLower: false
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 0
    name: date
    pattern: ""
    toLower: false
    type: basic
    weight: 10
  - applyFilter: false
    cardinalityThreshold: 0
    name: tags
    pattern: ""
    toLower: false
    type: basic
    weight: 80
  threshold: 80
  toLower: false
