baseURL: 'https://sudorandom.dev/'
languageCode: 'en-US'
theme: "hello-friend-ng"
author: 
  name: "sudorandom"
title: 'sudorandom.dev'
copyright: "All Rights Reserved"
IsMultiLingual: false
defaultContentLanguage: en
enableGitInfo: true

paginate: 50

staticDir: 
 - "static"

params:
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"

  Subtitle: "Depth-first search into networking, programming, random tech topics."
  Description: "Depth-first search into networking, programming, web development, Eve Online and random tech topics by a bored software engineer."
  homeSubtitle: "Depth-first search into networking, programming, random tech topics."
  ReadOtherPosts: "Read some other posts"
  defaultTheme: "dark"
  EnableThemeToggle: false
  gitUrl: "https://github.com/sudorandom/sudorandom.dev/commit/"
  EnableSharingButtons: true
  EnableGlobalLanguageMenu: false
  customCSS: ["css/style.css"]
  backgroundImage: "images/transparent_geo-mercator-small.webp"
  backgroundEffects: true
  showPosts: true
  tags: false
  contentTypeName: posts
# hideReadMore: true
  ReadMoreText: true
# ReadMore: "foo"
# socialIcons: true
# homeTitle: "Title"
# homeSubtitle: "Subtitle"
  fontAwesome:
    KitURL: "https://kit.fontawesome.com/0ed5cec925.js"
  ShowReadingTime: true
  LastModDisplay: false
  logo:
    logoText: "sudorandom.dev"
    logoCursorColor: "#ffffff"
  social:
    - name: "mastodon"
      url: "https://infosec.exchange/@sudorandom"
    - name: "github"
      url: "https://github.com/sudorandom"
    - name: "twitter"
      url: "https://twitter.com/sudorandom/"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sudorandom/"

  footer:
    showVersion: true
    socialIcons: true
    author: true
    rss: true
    trademark: true
    copyright: true
    bottomText: [
      # "Powered by <a href=\"http://gohugo.io\">Hugo</a>", 
      # "with <a href=\"#\">Hello-friend-4s3ti</a>",
    ]

taxonomies:
  category: "categories"
  tag: "tags"

menu:
  main:
    - identifier: "posts"
      name: "Archive"
      url: "/posts/"
      weight: 1
    - identifier: "portfolio"
      name: "Portfolio"
      url: "/portfolio/"
      weight: 2
    - identifier: "cv"
      name: "CV"
      url: "https://cv.sudorandom.dev"
      weight: 3
    - identifier: "shop"
      name: "Shop"
      url: "/shop/"
      weight: 4

markup:
  tableOfContents:
    endLevel: 4