name: build-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17.x

      # - name: Install cuttlebelle
      #   run: npm install cuttlebelle -g

      # - name: Build docs
      #   run: cuttlebelle

      - name: Configure git
        run: |
          touch site/.nojekyll
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout --orphan gh-pages
          git --work-tree site add --all
          git --work-tree site commit -m 'gh-pages'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
