name: Updates from Mastodon

on:
    schedule:
      - cron: "0 6 * * *"

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run mastodon
      run: make mastodon

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Mastodon
